### ISSUE TITLE
Search for :metal: returns the string and not the emoji

### ISSUE THREAD

**Issue by morganestes** [rkneufeld/alfred-emoji-characters-workflow#3]
When I do a search for an emoji that's defined in gemoji, but not listed in the workflow itself (like `:metal:`), the :metal: image appears in Alfred, but doesn't get copied to the clipboard. Instead, just the text of the search gets copied.

**Comment by rkneufeld** [comment]
I think there are some extra emojis in the gemoji library, that aren't *actual* emojis, but png hacks. Not sure if there is a way to filter them, though.

**Comment by morganestes** [comment]
Spent a few minutes looking and I could only think of one way, which is to filter based on the presence of the image in the gemoji directory. My ruby isn't great, but I'll submit a PR with what I have and let you take a look.
