### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by thedamon** [rkneufeld/alfred-emoji-characters-workflow#7]
It would be great if there were install instructions! I do not know how to get this into Alfred

I'd be happy to do a PR if someone can provide a reference to how generally to do this

**Comment by rkneufeld** [comment]
I have to be honest, I don't actually remember how to build it. I would gladly hand over the reigns or accept PRs improving the experience.

**Comment by blainesch** [comment]
I think you can upload artifacts to the [releases](https://github.com/rkneufeld/alfred-emoji-characters-workflow/releases) section of the repo. I'll generate a workflow real quick.

**Comment by blainesch** [comment]
The gem dependencies make this a little difficult. I'll see if I can make a pr to remove them.

**Comment by rmm5t** [comment]
> I have to be honest, I don't actually remember how to build it. I would gladly hand over the reigns or accept PRs improving the experience.

Please check out https://github.com/jsumners/alfred-emoji

If you've sunset this repository, we'd love a pointer over to jsumners/alfred-emoji in the README. I'm happy to submit a PR if that would help. Just let me know.

**Comment by rkneufeld** [comment]
@rmm5t I'd say its safe to say this repo is sunsetted. I'm traveling at the moment, but I'll gladly accept a PR pointing to the new repo.

**Comment by rmm5t** [comment]
@rkneufeld No problem. PR #8 submitted.
